version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing somethingg"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 130629727466.dkr.ecr.us-east-1.amazonaws.com
            - 130629727466.dkr.ecr.us-east-1.amazonaws.com/apachewebsiterepository
            build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - grep -Fq "MyServices" index.html
    post_build:
        commands:
            - echo "we are in the post build phase"
            
